[package]
name = "day-07"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
arrayvec = "0.4.6"
fxhash = "0.2.1"
rayon = "0.9.0"

[build-dependencies]
cc = "*"
